### ISSUE TITLE
Bouton Dark Mode

### ISSUE THREAD

**Issue by myoann** [ElmahdiK/japanim89#12]
En fait, ton composant ButtonThemeMode est un input avec une image, mais a quoi ca sert davoir un input ? A rien Elmahdi, a rien !

Donc ce que je te propose, c'est plutôt de créer un composant qui s'appelle IconButton.tsx et qui prend des props genre l'icone a afficher et l'action a faire, c'est tout

Donc au lieu dappeler ButtonThemeMode tu appeleras IconButton avec soit une icone soit l'autre, et ça appelera un truc genre setDarkMode 

https://github.com/ElmahdiK/japanim89/blob/afe7114bbe283af96344c21d792d3022299b7943/src/components/Buttons/ButtonThemeMode.tsx#L26

**Comment by ElmahdiK** [comment]
bien vu
