### ISSUE TITLE
Composants Contact

### ISSUE THREAD

**Issue by myoann** [ElmahdiK/japanim89#9]
Tu peux davantage découper ta page contact en composants.
Par exemple, un composant pour les Input ce serait deja bien

Tu peux faire aussi un composant Button pour les boutons

https://github.com/ElmahdiK/japanim89/blob/afe7114bbe283af96344c21d792d3022299b7943/src/app/contact/page.tsx#L25

**Comment by ElmahdiK** [comment]
Plus besoin pour le moment, j'ai supprimé cette page 👍
